language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55base qt55webkit-examples libgl1-mesa-dev desktop-file-utils
  - source /opt/qt*/bin/qt*-env.sh

script:
  # Workaround for https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627
  - cd /
  - sudo wget http://security.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg_1.17.5ubuntu5.8_amd64.deb
  - sudo dpkg-deb -x *.deb .
  - cd -
  # FIXME: Olivia needs mpv, and since the mpv project does not provide an AppImage yet, we are going to make a quick and dirty one
  # this is incredibly wasteful, as this mpv was built with --extra-cflags='-I/build/mpv-KeaQK0/mpv-0.29.1+git3~trusty/build_libs/include' --extra-ldflags='-L/build/mpv-KeaQK0/mpv-0.29.1+git3~trusty/build_libs/lib' --extra-libs=-ldl --prefix='/build/mpv-KeaQK0/mpv-0.29.1+git3~trusty/build_libs' --enable-static --disable-shared --enable-gpl --disable-debug --disable-doc --disable-programs --enable-libass --enable-libbs2b --enable-gcrypt --enable-libgme --enable-libgsm --enable-libmodplug --enable-ladspa --enable-libsoxr --enable-libssh --enable-openssl --enable-libdav1d --enable-libx264 --enable-libxvid --enable-nonfree --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libwavpack --enable-libtheora --enable-libtwolame --enable-libspeex
  # Possibly we would better compile our own, minimal one, which could also share the same Qt instance with Olivia
  - wget -c -nv https://raw.githubusercontent.com/AppImage/pkg2appimage/master/pkg2appimage
  - bash -ex pkg2appimage mpv.yml
  # Olivia
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install
  - mkdir -p appdir/usr/bin ; cp ./out/mpv*AppImage appdir/usr/bin/mpv
  - wget -c -nv "https://yt-dl.org/downloads/latest/youtube-dl" -O appdir/usr/bin/youtube-dl ; chmod +x appdir/usr/bin/youtube-dl 
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - wget -c -nv "https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64" -O ./appdir/AppRun ; chmod +x ./appdir/AppRun
  - find appdir/
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset LD_LIBRARY_PATH
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Olivia*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
