language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55base qt55webkit-examples libgl1-mesa-dev desktop-file-utils
  - source /opt/qt*/bin/qt*-env.sh

script:
  # FIXME: Olivia needs mpv, and since the mpv project does not provide an AppImage yet, we are going to make a quick and dirty one
  - wget -c -nv https://raw.githubusercontent.com/AppImage/pkg2appimage/master/pkg2appimage
  - bash -ex pkg2appimage mpv.yml
  # Olivia
  - qmake CONFIG+=release PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - mkdir -p appdir/usr/bin ; cp mpv*AppImage appdir/usr/bin/mpv
  - wget -c -nv "https://yt-dl.org/downloads/latest/youtube-dl -O appdir/usr/bin/youtube-dl" ; chmod +x appdir/usr/bin/youtube-dl 
  # wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - wget -c -nv "https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-x86_64" -O ./squashfs-root/AppRun ; chmod +x ./squashfs-root/AppRun
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset LD_LIBRARY_PATH
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Olivia*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
